### ISSUE TITLE
No output .CSV file

### ISSUE THREAD

**Issue by rgn-glitch** [PaperMtn/slack-watchman#19]
Hey There,

The following does not output to a .csv file to see results, only the number found.
--pii
--tokens
--financial

Can you assist please??

Thanks!

**Comment by PaperMtn** [comment]
Hey,

What version are you using? You can check by running `slack-watchman --version`

I've tested it on version 2.0.3 and the latest version 2.1.0 and it is working for me.

If you are using an old version, try updating to the latest version. If you used pip, it would be: `pip3 install --upgrade slack-watchman`

Let me know how it goes

**Comment by rgn-glitch** [comment]
Hi,

Thanks for your reply. 
I'm using the latest version 2.1.0
I've run apt-get update, along with pip3 install --upgrade slack-watchman.
No success.

For --tokens, it only outputs the AWS credentials to .csv not the other findings.
No .csv output for the above before mentioned. :(

**Comment by PaperMtn** [comment]
Can you let me know what OS/distro you're running, and perhaps give some example of the output you are getting?

Is there definitely some data being found in Slack for the time frame you have selected, but not written to .csv?

**Comment by rgn-glitch** [comment]
Distro: Kali GNU/Linux Rolling, Debian, 2020.2

Yes, their is definitely data being found in Slack for the time-frame specified, but not written to .csv

Example: --pii search will return 'X' amount of pages found for queries  "Finding ID taxpayer ID Number"
"Finding national insurance numbers" "Finding DOB" and "Finding passwords" With no .csv output provided.

**Comment by PaperMtn** [comment]
Ok, I think I see what is happening. The way that Slack Watchman works is that it uses search terms to query the Slack API and return data, which is then filtered using regex to find any matches. Look at this output from my testing Slack workspace:

```
Finding US social security numbers
+++++++++++++++++++++
1 page(s) found for query: ssn
1 matches found for ssn
CSV written: /Users/papermtn/potential_leaked_us_ssn_ssn.csv
1 page(s) found for query: social security
```
The Slack query `ssn` has returned one page of results, Slack Watchman pulls 100 results per page, but in reality one page may be for 1 or 2 results found using that query. The results returned are then searched using regex, and if anything matches, that is then written to CSV.

Notice that the query for `social security` returned 1 page, but there were no matches so nothing was written.

I hope this clears it up? Looks like everything is working as expected. I may play around with the wording in future versions if it is causing confusion.

**Comment by rgn-glitch** [comment]
Excellent, thanks for your help clearing that up 👍
