### ISSUE TITLE
Getting error 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by bhatisunil2706** [PaperMtn/slack-watchman#22]
I have installed slack-watchman. As soon as i run **slack-watchman --timeframe a --all** watchman starts but gives error.

Version: 2.3.1

Searching workspace: ****
Workspace URL: https://*****.com/

Getting everything...
+++++++++++++++++++++
Getting users
+++++++++++++++++++++
Getting channels
+++++++++++++++++++++
Getting admin users
+++++++++++++++++++++
'encoding' is an invalid keyword argument for this function

Please let me now how can we fix this.

**Python version used - Python 2.7.16**

**Comment by PaperMtn** [comment]
It's probably a Python version issue, as Slack Watchman isn't Python 2 compatible. Is Python 3 available to you?
