### ISSUE TITLE
Add base rule set sources

### ISSUE THREAD

**Issue by dwisiswant0** [PaperMtn/slack-watchman#3]
Can you please add this ruleset regexes from truggleHog?
https://github.com/dxa4481/truffleHogRegexes/blob/master/truffleHogRegexes/regexes.json

I think it would be better if we could add a custom pattern _(like how [gf](https://github.com/tomnomnom/gf) works)_, and selection for regex by comma-separated argument, for ex `--find aws,gcp` instead of `-a` or `-g`.

**Comment by PaperMtn** [comment]
I'll have a look at those regexes, there are also some more ideas for things to search for as well.

I'll also think about changes for arguments

**Comment by PaperMtn** [comment]
More searches have been added, some inspired from the truffleHog ruleset.

Newer versions also implement a new argument scheme, making it more manageable
