### ISSUE TITLE
Enhancement - App Permissions

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [PaperMtn/slack-watchman#36]
Hi,
Is is possible to get a report on the apps installed (any details that go with that) and their permissions?  
Reason being some apps may have overly permissive permissions and it would be good to know which ones.

Other things I can think:
User details - some PII in user details such as phone numbers/skype etc.

Anyway, loving this app. Its currently helping me loads with a task Ive been given.

**Comment by PaperMtn** [comment]
Unfortunately this is not possible without the Enterprise Grid API, which I haven't used in Slack Watchman to make it compatible with any version of Slack.

Perhaps in the future I will integrate Enterprise Grid features.
