### ISSUE TITLE
Support getting Slack token from args/env var

### ISSUE THREAD

**Issue by j-boivie** [PaperMtn/slack-watchman#5]
It would be really nice if it was possible to get the slack token through another method than a file, such as a CLI arg or environment variable, f.ex. for running this unsupervised in a container or similar.

**Comment by PaperMtn** [comment]
Yeah I see where you're coming from, it would make it easier to run under CICD as well.

I like the idea of an environment variable more than an argument I think. This is definitely something I will be adding to a future release.

**Comment by j-boivie** [comment]
@PaperMtn I opened #6 as a way to implement this without any major changes to the rest of the code. Hope it can be useful! 😄

**Comment by PaperMtn** [comment]
This has been implemented in the latest release
