### ISSUE TITLE
Add parameter to specify signature path

### ISSUE THREAD

**Issue by GabrielPadis-CS** [PaperMtn/slack-watchman#51]
**Is your feature request related to a problem? Please describe.**
On a read-only filesystem (in my case, on Kubernetes), launching `slack-watchman` will fail because it tries to download signatures directly on the filesystem.
```python
self.application_path = str((Path(__file__).parents[2]).resolve())
...
sig_dir = os.path.join(self.application_path, 'watchman-signatures/')
```
[source code](https://github.com/PaperMtn/slack-watchman/blob/a9c6b3aa6ab08022dec51354273acee2df456bb6/src/slack_watchman/signature_updater.py#L25)
The path is hardcoded to be in the directory that is two levels up from the directory where the script is located.

**Describe the solution you'd like**
On read-only filesystem, best practice is to mount a writable directory as needed (for example to store the output of the scan).

It would be best to add an option to `slack-watchman` like `--signature-path` that would allow to specify a path where the signatures would be downloaded and read from.

**The hack**
To bypass this, it is possible to make the default path a mount to with an EmptyDir pointing to `/usr/local/lib/python3.12/watchman-signatures/` because my Docker image is pulled from `python:3.12-slim-bullseye`. That way, when launched, it can write to the default directory where it is installed (with `pip install`). It is not a pretty solution.

**Describe alternatives you've considered**
Have been considered:
- Downloading and extracting the signatures at the build time of the Dockerfile
  -  -> It did not work for me and would not guarantee the freshness of the signatures.Add any other context or screenshots about the feature request here.
- Running `slack-watchman` during the build time of the Docker image to have it download the signatures on the filesystem 
  - -> It would require a valid Slack token to be hardcoded into the Docker image and the source code which is not a good practice. It would also not guarantee the freshness of the signatures.

**Additional context**
Here are the error logs when it fails to download the signatures:
```
{"timestamp": "2024-08-20 09:14:48,378", "level": "SUCCESS", "message": "Slack Watchman started execution"}
{"timestamp": "2024-08-20 09:14:48,378", "level": "INFO", "message": "Version: 4.0.2"}
{"timestamp": "2024-08-20 09:14:48,378", "level": "INFO", "message": "Created by: PaperMtn - papermtn@protonmail.com"}
{"timestamp": "2024-08-20 09:14:48,378", "level": "INFO", "message": "Searching workspace: xxxxxxx"}
{"timestamp": "2024-08-20 09:14:48,379", "level": "INFO", "message": "Workspace URL: https://xxxxxxxx.slack.com/"}
{"timestamp": "2024-08-20 09:14:48,379", "level": "INFO", "message": "Downloading signature file updates"}
{"timestamp": "2024-08-20 09:14:48,676", "level": "CRITICAL", "message": "Error while creating the signature-base directories"}
```

**Comment by PaperMtn** [comment]
Hi @GabrielPadis-CS, thanks for raising this. Its an interesting issue that I hadn't considered before. I'll think about your suggestion, but I think I will also have a look at a way of implementing getting the signatures without writing them to file locally.

**Comment by PaperMtn** [comment]
Hey @GabrielPadis-CS, based on your suggestion, I decided there is no real reason for signatures to be written to disk at all. Signatures are now downloaded and stored in memory with the latest release of Slack Watchman. This should hopefully solve the issue with running on read-only filesystems.

Hope this fits your needs, give it a go and let me know.

**Comment by GabrielPadis-CS** [comment]
Hi @PaperMtn,
Thanks for changing this behavior ([commit](https://github.com/PaperMtn/slack-watchman/commit/258642216d3bc0784578bdea3c19707214b46fed)) quite rapidly! I have tested the version `4.1.2` on my infrastructure and I can confirm that it works and that I no longer need to add a volume on a hard-coded path :smile: 
I am closing this issue then, thanks!
